backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
local_backend: {{ eq false hugo.IsProduction }}
media_folder: "static/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "index" # Used in routes, e.g., /admin/collections/blog
    label: "Main Focus" # Used in the UI
    folder: "content" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Type", name: "type", widget: "hidden"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Menu Name", name: "menu", widget: "hidden"}
      - {label: "Menu Weight", name: "weight", widget: "hidden"}
      - {label: "Banner Image", name: "banner_img", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "homepage" # Used in routes, e.g., /admin/collections/blog
    label: "Home Page" # Used in the UI
    folder: "content/homepage" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Icon", name: "icon", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

      
  - name: "about" # Used in routes, e.g., /admin/collections/blog
    label: "About Page" # Used in the UI
    create: false # Allow users to create new documents in this collection
    files: 
    - file: /content/about/history.md
      name: "history"
      label: "History"
      fields:
       - {label: Title, name: title, widget: string}
       - {label: History Image, name: history_img, widget: image}
       - {label: "Body", name: "body", widget: "markdown"}

    - file: /content/about/membershipstruct.md
      name: "membershipstruct"
      label: "Membership Structure"
      fields:
       - {label: Title, name: title, widget: string}
       - {label: Membership Structure Image, name: membershipstruct_img, widget: image}
       - {label: "Body", name: "body", widget: "markdown"}

    - file: /content/about/management.md
      name: "management"
      label: "Management"
      fields:
        - {label: Title, name: title, widget: string}
        - {label: Management Image, name: management_img, widget: image}
        - {label: "Body", name: "body", widget: "markdown"}

    - file: /content/about/secretariate.md
      name: "secrtariate"
      label: "Secretariate"
      fields:
        - {label: Title, name: title, widget: string}
        - {label: Secretariate Image, name: secretariate_img, widget: image}
        - {label: "Body", name: "body", widget: "markdown"}

        
  - name: "partners" # Used in routes, e.g., /admin/collections/blog
    label: "Partners Page" # Used in the UI
    folder: "content/partners" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Read More", name: "read_more", widget: "string"}
      - {label: "Address", name: "address", widget: "string"}
      - {label: "Email", name: "email", widget: "string"}
      - {label: "Telephone", name: "tel", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  